/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Hafiz Caniago
 */
public class Login extends javax.swing.JFrame {

    Statement st;
    ResultSet rs;
    Koneksi kon;

    /**
     * Creates new form Login
     */
    public Login() {
        kon = new Koneksi();
        initComponents();
        level();
        setLocationRelativeTo(this);

    }

    public void level() {
        try {
            st = kon.con.createStatement();
            String query = "SELECT * FROM tbl_level";
            rs = st.executeQuery(query);
            while (rs.next()) {
                Llevel.addItem(rs.getString("LEVEL"));
            }
            rs.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Llevel = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        log.setBackground(new java.awt.Color(0, 204, 255));
        log.setText("LOGIN");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        getContentPane().add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 220, 40));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 0, -1, 300));

        Llevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Posisi" }));
        Llevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        getContentPane().add(Llevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 190, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbc/Web-Server-Vs-Your-Computer-Why-You-Need-a-Server-to-Host-a-Website-BLOG-removebg-preview.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 600, 430));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbc/permission (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("username");
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, 30));

        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("password");
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        try {
            st = kon.con.createStatement();
            String sql = "SELECT * FROM tbl_user WHERE USERNAME='" + username.getText() + "' AND PASSWORD='" + password.getText() + "'";
            rs = st.executeQuery(sql);
            if (rs.next()) {
                if (username.getText().equals(rs.getString("USERNAME")) && password.getText().equals(rs.getString("PASSWORD")) && Llevel.getSelectedItem().equals("ADMIN")) {
                    if (rs.getString("ID_LEVEL").equals("1")) {
                        userlogin.setUserLogin(rs.getString("NAMA_USER"));
                        FUser a = new FUser();
                        a.setVisible(true);
                        this.dispose();
                        JOptionPane.showMessageDialog(null, "Welcome " + rs.getString("NAMA_USER"));
                    } else if (rs.getString("ID_LEVEL").equals("2")) {
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    } else if (rs.getString("ID_LEVEL").equals("3")) {
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    }
                } else if (username.getText().equals(rs.getString("USERNAME")) && password.getText().equals(rs.getString("PASSWORD")) && Llevel.getSelectedItem().equals("GUDANG")) {
                    if (rs.getString("ID_LEVEL").equals("2")) {
                        userlogin.setUserLogin(rs.getString("NAMA_USER"));
                        iduser.setiduser(rs.getString("ID_USER"));
                        Fbarang b = new Fbarang();
                        b.setVisible(true);
                        this.dispose();
                        JOptionPane.showMessageDialog(null, "Welcome " + rs.getString("NAMA_USER"));
                    } else if (rs.getString("ID_LEVEL").equals("1")) {
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    } else if (rs.getString("ID_LEVEL").equals("3")) {
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    }
                } else if (username.getText().equals(rs.getString("USERNAME")) && password.getText().equals(rs.getString("PASSWORD")) && Llevel.getSelectedItem().equals("KASIR")) {
                    if (rs.getString("ID_LEVEL").equals("3")) {
                        userlogin.setUserLogin(rs.getString("NAMA_USER"));
                        iduser.setiduser(rs.getString("ID_USER"));
                        Fkasir c = new Fkasir();
                        c.setVisible(true);
                        this.dispose();
                        JOptionPane.showMessageDialog(null, "Welcome " + rs.getString("NAMA_USER"));
                    } else if (rs.getString("ID_LEVEL").equals("1")) {
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    } else if (rs.getString("ID_LEVEL").equals("2")) {
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Username atau Password tidak terdaftar");
            }
            rs.close();
            st.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_logActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Llevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton log;
    private javax.swing.JTextField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
